# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20170723_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag_set',
            field=models.ManyToManyField(to='board.Tag'),
        ),
    ]
